# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- binary: urnaus
  main: ./cmd/uranus
  goos:
     - windows
     - darwin
     - linux
  goarch:
     - amd64
     - 386
- binary: uranuscli
  main: ./cmd/uranuscli
  goos:
     - windows
     - darwin
     - linux
  goarch:
     - amd64
     - 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'