Vagrant.configure("2") do |config|
    #Nodes 101 102 ...
    (1..5).each do |i|

        config.vm.define "node#{i}" do |node|

        # vm Box
        node.vm.box = "ubuntu/trusty64"

        # vm hoste name 
        node.vm.hostname="node#{i}"

        # vm ip
        #node.vm.network "private_network", ip: "192.168.59.10#{i}"
        node.vm.network "public_network"

        # share data dir
        node.vm.synced_folder "..", "/opt/gopath/src/github.com/UranusBlockStack/uranus"

        # VirtaulBox configuration
        node.vm.provider "virtualbox" do |v|

            # name
            v.name = "node#{i}"

            # memory
            #v.memory = 2048

            # cpu
            v.cpus = 1
        end
  
        # software installation and configuration
        node.vm.provision "shell", inline: <<-SHELL
          cd /opt/gopath/src/github.com/UranusBlockStack/uranus/devenv
          chmod +x ./setup.sh
          ./setup.sh
        SHELL

        end
    end
end